Blog/blueprints/admin.py
import os
from flask import Blueprint, flash, render_template, url_for, redirect, request, current_app
from flask_login import login_required, current_user
from Blog.form import PostForm, CategoryForm, SettingForm
from Blog.models import Category, Post, Comment, Message, User
from Blog.extensions import db
from Blog.utils import redirect_back, permission_required

admin_bp = Blueprint('admin',__name__)

@admin_bp.before_request
@login_required
@permission_required('ADMINISTER')
def login_protect():
	pass

@admin_bp.route('/posts')
def manage_post():
	page = request.args.get('page', 1, type=int)
	pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
		page, per_page=current_app.config['BLOG_MANAGE_POST_PER_PAGE'])
	posts = pagination.items
	return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/new_post', methods=['GET', 'POST'])
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		title = form.title.data
		category = Category.query.get(form.category.data)
		body = form.body.data
		# print("时间",form.uploadtime.data)
		print(type(form.uploadtime.data))
		uploadtime = form.uploadtime.data if form.uploadtime.data else None
		post = Post(title=title, body=body, category=category, timestamp=uploadtime)
		db.session.add(post)
		db.session.commit()
		flash('Post created.', 'success')
		return redirect(url_for('blog.show_post', param=post.title))
	return render_template('admin/post.html', form=form)

@admin_bp.route('/post/<param>', methods=['GET'])
def get_post(param):
	form = PostForm()
	item = Post.query.filter_by(title=param).first_or_404()
	if item:
		form.title.data = item.title
		form.body.data = item.body
		form.category.data = item.category_id
		return render_template('admin/post.html', form=form, post=item)
	return render_template('admin/post.html', form=form)

@admin_bp.route('/post/<param>', methods=['POST'])
def edit_post(param):
	form = PostForm()
	item = Post.query.filter_by(title=param).first_or_404()
	if form.validate_on_submit() and item:
		if form.submit.data:
			item.title = form.title.data
			item.category = Category.query.get(form.category.data)
			item.body = form.body.data
			if request.form.get('uploadtime'):
				item.timestamp = form.uploadtime.data
			db.session.commit()
			flash('Post is updated.', 'success')
	return redirect(url_for('blog.show_post', param=item.title))

@admin_bp.route('/post/<param>?_method=DELETE', methods=['POST'])
def delete_post(param):
	item = Post.query.filter_by(title=param).first_or_404()
	db.session.delete(item)
	db.session.commit()
	flash('Post is deleted.', 'success')
	return redirect(url_for('admin.manage_post'))

@admin_bp.route('/categories')
def manage_category():
	categories = Category.query.all()
	return render_template('admin/manage_category.html', categories=categories)

@admin_bp.route('/new_category', methods=['GET', 'POST'])
def new_category():
	form = CategoryForm()
	if form.validate_on_submit():
		name = request.form['name']
		if name != 'Default' :
			category = Category(name=name)
			db.session.add(category)
			db.session.commit()
			flash('Category updated.', 'success')
			return redirect(url_for('.manage_category'))
	return render_template('admin/category.html', form=form)

@admin_bp.route('/category/<category_id>', methods=['GET', 'POST'])
def edit_category(category_id):
	form = CategoryForm()
	category = Category.query.get_or_404(category_id)
	if category.id == 1:
		flash('You can not edit the default category.', 'warning')
		return redirect_back()
	if form.validate_on_submit():
		category.name = request.form['name']
		db.session.commit()
		flash('Category updated.', 'success')
		return redirect(url_for('.manage_category'))
	form.name.data = category.name
	return render_template('admin/category.html', form=form)

@admin_bp.route('/category/<category_id>?_method=DELETE', methods=['POST'])
def delete_category(category_id):
	category = Category.query.get_or_404(category_id)
	if category.id == 1:
		flash('You can not delete the default category.', 'warning')
		return redirect_back()
	category.delete()
	flash('Category deleted.', 'success')
	return redirect(url_for('.manage_category'))

@admin_bp.route('/comments')
def manage_comment():
	page = request.args.get('page', 1, type=int)
	per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
	pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
	comments = pagination.items
	return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)

@admin_bp.route('/comment/<comment_id>?_method=DELETE', methods=['POST'])
def delete_comment(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	#Don't delete comment, just modify their body to below.
	comment.body = "Comment has been deleted"
	# db.session.delete(comment)
	db.session.commit()
	flash('Comment deleted.', 'success')
	return redirect_back()

@admin_bp.route('/comment/setting/<post_id>', methods=['POST'])
def set_comment(post_id):
	post = Post.query.get_or_404(post_id)
	if post.can_comment:
		post.can_comment = False
		flash('Comment disabled.', 'success')
	else:
		post.can_comment = True
		flash('Comment enabled.', 'success')
	db.session.commit()
	return redirect_back()

@admin_bp.route('/message')
def manage_message():
	page = request.args.get('page', 1, type=int)
	per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
	pagination = Message.query.order_by(Message.timestamp.desc()).paginate(page, per_page=per_page)
	messages = pagination.items
	return render_template('admin/manage_message.html', messages=messages, pagination=pagination)

@admin_bp.route('/message/<message_id>?_method=DELETE', methods=['POST'])
def delete_message(message_id):
	message = Message.query.get_or_404(message_id)
	db.session.delete(message)
	db.session.commit()
	flash('Message deleted.', 'success')
	return redirect_back()

@admin_bp.route('/setting', methods=['GET','POST'])
def personal_setting():
	form = SettingForm()
	if form.validate_on_submit():
		person = User.query.filter_by(email=current_user.email).first()
		if request.form['password'] and request.form['password2'] and request.form['password'] == request.form['password2']:
			print("yes")
			person.password = request.form['password']
		person.username = request.form['username'] or current_user.username
		person.image = request.form['image']
		db.session.commit()
		flash('Setting modify.', 'success')
	form.username.data = current_user.username
	return render_template('admin/setting.html', form=form)


@admin_bp.route('/upload', methods=['GET', 'POST'])
def upload():
	if request.method == 'POST' and 'file' in request.files:
		f = request.files.get('file')
		filename = f.filename
		filetype = filename.split('.', 1)[1]
		if filetype in ['md','txt']:
			path = os.path.join(current_app.config['FILE_UPLOAD_PATH'], filename)
		
		else:
			path = os.path.join(current_app.config['IMAGE_UPLOAD_PATH'], filename)
		f.save(path)
		if filetype in ['md','txt']:
			with open(path, 'r', encoding='UTF-8', errors='ignore') as essay:
				s = essay.read()
				print(s)
				title = filename.split('.', 1)[0]
				new_post = Post(title=title,body=s)
				db.session.add(new_post)
				db.session.commit()
	return render_template('admin/upload.html')

Blog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for, session, jsonify
from flask_login import current_user, login_required, login_user
from Blog.models import Post, Category, Comment, User
from Blog.utils import redirect_back
from Blog.extensions import db
from Blog.form import CommentForm, CommentFormHidden
from Blog.emails import send_someone_connect_email

blog_bp = Blueprint('blog', __name__)

@blog_bp.route('/posts')
def blogs():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/blog.html', pagination=pagination, posts=posts)

@blog_bp.route('/category/<int:category_id>', methods=['GET', 'POST'])
def categories(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.filter_by(category_id=category_id).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', pagination=pagination, posts=posts, category=category)

@blog_bp.route('/post/<param>', methods=['GET'])
def show_post(param):
    post = Post.query.filter_by(title=param).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    comment_pagination = Comment.query.filter_by(post_id=post.id).order_by(Comment.timestamp.desc()).paginate(
        page, per_page)
    comments = comment_pagination.items
    if not current_user.is_anonymous or 'browser_email' in session:
        form = CommentFormHidden()
        form.email.data = current_user.email if not current_user.is_anonymous else session['browser_email']
    else:
        form = CommentForm()
    try:
        form.name.data = current_user.username
    except:
        form.name.data = session['browser_user'] if ('browser_user' in session) else None
    return render_template('blog/post.html', pagination=comment_pagination, post=post, comments=comments, form=form)

@blog_bp.route('/post/<param>/comment', methods=['POST'])
def leave_comment(param):
    post = Post.query.filter_by(title=param).first_or_404()
    email = request.form.get('email', None)
    user = User.query.filter_by(email=email).first()
    if user and not user.confirmed:
        login_user(user)
        session.pop('browser_email',None)
        return redirect(url_for("auth.unconfirmed"))
    if not user:
        author = request.form.get('name', None)
        user = User(username=author, email=email)
    else:
        author = user.username
    body = request.form.get('body', None)
    comment = Comment(body=body, post=post, author_id=user.id)
    db.session.add(comment)
    replied_id = request.form.get('be_reply', None)
    if replied_id:
        replied_comment = Comment.query.get_or_404(replied_id)
        comment.replied = replied_comment
    if request.form.get('remember', None):
        session['browser_email'] = email
        session['browser_user'] = author
    db.session.commit()
    return redirect(url_for('blog.show_post', param=post.title) + '#comments')


@blog_bp.route('/reply')
def reply_comment():
    comment_id = request.args.get('comment_id')
    if comment_id:
        replied_comment = Comment.query.get_or_404(comment_id)
        return render_template('blog/_reply.html', comment=replied_comment)
    print(comment_id)
    return comment_id
    # comment = Comment.query.get_or_404(comment_id)
    # post = Post.query.get_or_404(comment.post_id)
    # print(comment.post_id)
    # if not comment.post.can_comment:
    #     flash('Comment is disabled.', 'warning')
    #     return redirect(url_for('blog.show_post', param=comment.post.title))
    # return redirect(
    #     url_for('blog.show_post', param=post.title, reply=comment_id) + '#comment-form')


@blog_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Enter keyword about post, user or comment.', 'warning')
        return redirect_back()
    category = request.args.get('category', 'post')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'comment':
        pagination = Comment.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Post.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('blog/search.html', q=q, results=results, pagination=pagination, category=category)


@blog_bp.route('/test')
def test():
    return jsonify({"a":1})

    

Blog/blueprints/index.py
from flask import flash, url_for, redirect, request, current_app, render_template, jsonify
from flask.blueprints import Blueprint
from Blog.models import Post, Message
from Blog.form import HelloForm
from Blog.extensions import db, csrf
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter
index_bp = Blueprint('index',__name__)


@index_bp.route('/', methods=['GET'])
def index():
    last = Post.query.order_by(Post.timestamp.desc()).first()
    form = HelloForm()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MESSAGE_PER_PAGE']
    pagination = Message.query.order_by(Message.timestamp.desc()).paginate(page, per_page=per_page)
    messages = pagination.items

    return render_template('index.html', post=last, pagination=pagination, messages=messages, form=form)

@csrf.exempt
@index_bp.route('/index/message', methods=['POST'])
def message():
    data = request.get_json()
    if request.method == 'POST':
        name = data['name']
        body = data['body']
        message = Message(body=body, name=name)
        db.session.add(message)
        db.session.commit()
        # return jsonify({'result' : 'yes'})
        # flash('Your message have been sent to the world!')
        return render_template('_message.html', message=message)
    return jsonify({'result':'error'})

Blog/templates/_message.html
<div class="list-group-item list-group-item-action flex-column">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1 text-success">{{ message.name }}
        </h5>
        <small data-toggle="tooltip" data-placement="top"
               data-timestamp="{{ message.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"
               data-delay="100">
            {{ moment(message.timestamp).fromNow(refresh=True) }}
        </small>
    </div>
    <p class="mb-1">{{ message.body }}</p>
</div>

{% block scripts %}
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock %}

Blog/templates/base.html
<!doctype html>
{% from 'bootstrap/nav.html' import render_nav_item %}
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %} - Fanco's study room</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}">
    {% block styles %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock styles %}
    {% endblock head %}
</head>
<body>
<button id="scroll2top" class="btn btn-danger" title="Go to top">TOP</button>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('index.index') }}">Fanco's study room</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                {{ render_nav_item('index.index', 'Home') }}
                {{ render_nav_item('blog.blogs', 'Blog') }}
                {% if current_user.is_admin %}
                {{ render_nav_item('admin.upload', 'Upload') }}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <img class="img-display" width="38" height="38" src="{{ current_user.image }}">

                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button"
                       aria-expanded="false">
                        {{ current_user.username }} <span class="caret"></span>
                    </a>
                    {% if current_user.is_admin %}
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">New Post</a>
                        <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">Post</a>
                        <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">Category</a>
                        <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">Comment</a>
                        <a class="dropdown-item" href="{{ url_for('admin.manage_message') }}">Message
                                                                                              {% if unread_comments %}
                            <span class="badge badge-success">{{ unread_comments }}</span>
                                                                                              {% endif %}
                        </a>
                        <a class="dropdown-item" href="{{ url_for('admin.personal_setting') }}">Setting</a>
                    </div>
                    {% endif %}
                </li>

                {{ render_nav_item('auth.logout', 'Logout') }}
                {% else %}
                {{ render_nav_item('auth.login', 'Login') }}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock nav %}

<main class="container main">
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }} flashed_message" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
    {% endfor %}
    {% block content %}{% endblock content %}

</main>

{% block footer %}
<footer>
    <p class="float-left">
        <small> &copy; All rights reserved. <a href="http://fanco.ink" title="To my blog">Fanco</a> -
            <a href="https://github.com/fancofang" title="Fork me on GitHub">GitHub</a>
        </small>
    </p>
</footer>
{% endblock footer %}

{% block scripts %}

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
<script type="text/javascript">
    var reply_url = "{{ url_for('blog.reply_comment') }}";
    var message_url = "{{ url_for('index.message') }}";
</script>
{% endblock %}
</body>
</html>

Blog/templates/index.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pager %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="page-header">
        <h4 class="text-muted">Latest:</h4>
    </div>
    <div class="row">
        <div class="col-sm-10">
            {% if post %}
                <h3 class="text-primary"><a href="{{ url_for('blog.show_post', param=post.title) }}">{{ post.title }}</a></h3>
                <p>
                    {{ post.body|striptags|truncate }}
                    <small><a href="{{ url_for('blog.show_post', param=post.title) }}">Read More</a></small>
                </p>
                <small>
                    Comments: <a href="{{ url_for('blog.show_post', param=post.title) }}">{{ post.comments|length }}</a>&nbsp;&nbsp;
                    Category: <a href="{{ url_for('blog.show_post', param=post.title) }}">{{ post.category.name }}</a>
                </small>
            {% else %}
                <div class="tip">
                    <h5>No posts yet.</h5>
                    {% if current_user.is_admin %}
                        <a href="{{ url_for('admin.new_post') }}">Write Now</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
        <div class="col-sm-2">
            <img class="pure-img pure-img-responsive" src="/static/img/portrait.jpg" alt="Logo">
        </div>
    </div>
    <hr>
    <div class="page-header">
        <h4 class="text-muted">Leave a comment:</h4>
    </div>
    <div id="message_area" class="row">
        <div id="show_message" class="col-sm-7">
            {% for message in messages %}
                <div class="list-group-item list-group-item-action flex-column">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1 text-success">{{ message.name }}
                        </h5>
                        <small data-toggle="tooltip" data-placement="top"
                               data-timestamp="{{ message.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}"
                               data-delay="100">
                            {{ moment(message.timestamp).fromNow(refresh=True) }}
                        </small>
                    </div>
                    <p class="mb-1">{{ message.body }}</p>
                </div>
            {% endfor %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-5 edit_message" id="message_form">
            {{ render_form(form, id="message_form") }}
        </div>

    </div>
{% endblock %}


{{ render_form(form) }}

Blog/templates/macros.html
{% macro post_card(post) %}
    <div>
        <h3 class="text-primary"><a href="{{ url_for('blog.show_post', param=post.title) }}">{{ post.title }}</a></h3>
        <p>
            {% if post.body_html %}
                {{ post.body_html | safe |striptags|truncate }}
            {% else %}
                {{ post.body|striptags|truncate }}
            {% endif %}
            <small><a href="{{ url_for('blog.show_post', param=post.title) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('blog.show_post', param=post.title) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a href="{{ url_for('.categories', category_id=post.category_id) }}">{{ post.category.name }}</a>&nbsp;&nbsp;
            Time: <a href="#">{{ moment(post.timestamp).format('LL') }}</a>
        </small>
    </div>
    <hr>
{% endmacro %}

{% macro user_card(user) %}
    <div>
        <h5>{{ user.username }}</h5>
    </div>
    <hr>
{% endmacro %}

{% macro comment_card(comment) %}
    <div>
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=comment.post.id) }}">{{ comment.post.title }}</a></h3>
        <p>Reviewer: {{ comment.author.username }}</p>
        <p>Comment: <a href="{{ url_for('.show_post', post_id=comment.post.id) }}#comments">{{ comment.body }}</a></p>
    </div>
    <hr>
{% endmacro %}