Blog/blueprints/admin.py
import os
from flask import Blueprint, flash, render_template, url_for, redirect, request, current_app
from flask_login import login_required, current_user
from Blog.form import PostForm, CategoryForm, SettingForm
from Blog.models import Category, Post, Comment, Message, User
from Blog.extensions import db
from Blog.utils import redirect_back, permission_required

admin_bp = Blueprint('admin',__name__)

@admin_bp.before_request
@login_required
@permission_required('ADMINISTER')
def login_protect():
	pass

@admin_bp.route('/posts')
def manage_post():
	page = request.args.get('page', 1, type=int)
	pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
		page, per_page=current_app.config['BLOG_MANAGE_POST_PER_PAGE'])
	posts = pagination.items
	return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/new_post', methods=['GET', 'POST'])
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		title = form.title.data
		category = Category.query.get(form.category.data)
		body = form.body.data
		# print("时间",form.uploadtime.data)
		print(type(form.uploadtime.data))
		uploadtime = form.uploadtime.data if form.uploadtime.data else None
		post = Post(title=title, body=body, category=category, timestamp=uploadtime)
		db.session.add(post)
		db.session.commit()
		flash('Post created.', 'success')
		return redirect(url_for('blog.show_post', param=post.title))
	return render_template('admin/post.html', form=form)

@admin_bp.route('/post/<param>', methods=['GET'])
def get_post(param):
	form = PostForm()
	item = Post.query.filter_by(title=param).first_or_404()
	if item:
		form.title.data = item.title
		form.body.data = item.body
		form.category.data = item.category_id
		return render_template('admin/post.html', form=form, post=item)
	return render_template('admin/post.html', form=form)

@admin_bp.route('/post/<param>', methods=['POST'])
def edit_post(param):
	form = PostForm()
	item = Post.query.filter_by(title=param).first_or_404()
	if form.validate_on_submit() and item:
		if form.submit.data:
			item.title = form.title.data
			item.category = Category.query.get(form.category.data)
			item.body = form.body.data
			if request.form.get('uploadtime'):
				item.timestamp = form.uploadtime.data
			db.session.commit()
			flash('Post is updated.', 'success')
	return redirect(url_for('blog.show_post', param=item.title))

@admin_bp.route('/post/<param>?_method=DELETE', methods=['POST'])
def delete_post(param):
	item = Post.query.filter_by(title=param).first_or_404()
	db.session.delete(item)
	db.session.commit()
	flash('Post is deleted.', 'success')
	return redirect(url_for('admin.manage_post'))

@admin_bp.route('/categories')
def manage_category():
	categories = Category.query.all()
	return render_template('admin/manage_category.html', categories=categories)

@admin_bp.route('/new_category', methods=['GET', 'POST'])
def new_category():
	form = CategoryForm()
	if form.validate_on_submit():
		name = request.form['name']
		if name != 'Default' :
			category = Category(name=name)
			db.session.add(category)
			db.session.commit()
			flash('Category updated.', 'success')
			return redirect(url_for('.manage_category'))
	return render_template('admin/category.html', form=form)

@admin_bp.route('/category/<category_id>', methods=['GET', 'POST'])
def edit_category(category_id):
	form = CategoryForm()
	category = Category.query.get_or_404(category_id)
	if category.id == 1:
		flash('You can not edit the default category.', 'warning')
		return redirect_back()
	if form.validate_on_submit():
		category.name = request.form['name']
		db.session.commit()
		flash('Category updated.', 'success')
		return redirect(url_for('.manage_category'))
	form.name.data = category.name
	return render_template('admin/category.html', form=form)

@admin_bp.route('/category/<category_id>?_method=DELETE', methods=['POST'])
def delete_category(category_id):
	category = Category.query.get_or_404(category_id)
	if category.id == 1:
		flash('You can not delete the default category.', 'warning')
		return redirect_back()
	category.delete()
	flash('Category deleted.', 'success')
	return redirect(url_for('.manage_category'))

@admin_bp.route('/comments')
def manage_comment():
	page = request.args.get('page', 1, type=int)
	per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
	pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
	comments = pagination.items
	return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)

@admin_bp.route('/comment/<comment_id>?_method=DELETE', methods=['POST'])
def delete_comment(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	#Don't delete comment, just modify their body to below.
	comment.body = "Comment has been deleted"
	# db.session.delete(comment)
	db.session.commit()
	flash('Comment deleted.', 'success')
	return redirect_back()

@admin_bp.route('/comment/setting/<post_id>', methods=['POST'])
def set_comment(post_id):
	post = Post.query.get_or_404(post_id)
	if post.can_comment:
		post.can_comment = False
		flash('Comment disabled.', 'success')
	else:
		post.can_comment = True
		flash('Comment enabled.', 'success')
	db.session.commit()
	return redirect_back()

@admin_bp.route('/message')
def manage_message():
	page = request.args.get('page', 1, type=int)
	per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
	pagination = Message.query.order_by(Message.timestamp.desc()).paginate(page, per_page=per_page)
	messages = pagination.items
	return render_template('admin/manage_message.html', messages=messages, pagination=pagination)

@admin_bp.route('/message/<message_id>?_method=DELETE', methods=['POST'])
def delete_message(message_id):
	message = Message.query.get_or_404(message_id)
	db.session.delete(message)
	db.session.commit()
	flash('Message deleted.', 'success')
	return redirect_back()

@admin_bp.route('/setting', methods=['GET','POST'])
def personal_setting():
	form = SettingForm()
	if form.validate_on_submit():
		person = User.query.filter_by(email=current_user.email).first()
		if request.form['password'] and request.form['password2'] and request.form['password'] == request.form['password2']:
			print("yes")
			person.password = request.form['password']
		person.username = request.form['username'] or current_user.username
		person.image = request.form['image']
		db.session.commit()
		flash('Setting modify.', 'success')
	form.username.data = current_user.username
	return render_template('admin/setting.html', form=form)


@admin_bp.route('/upload', methods=['GET', 'POST'])
def upload():
	if request.method == 'POST' and 'file' in request.files:
		f = request.files.get('file')
		filename = f.filename
		filetype = filename.split('.', 1)[1]
		if filetype in ['md','txt']:
			path = os.path.join(current_app.config['FILE_UPLOAD_PATH'], filename)
		
		else:
			path = os.path.join(current_app.config['IMAGE_UPLOAD_PATH'], filename)
		f.save(path)
		if filetype in ['md','txt']:
			with open(path, 'r', encoding='UTF-8', errors='ignore') as essay:
				s = essay.read()
				print(s)
				title = filename.split('.', 1)[0]
				new_post = Post(title=title,body=s)
				db.session.add(new_post)
				db.session.commit()
	return render_template('admin/upload.html')

Blog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, flash, redirect, url_for, session, jsonify
from flask_login import current_user, login_required, login_user
from Blog.models import Post, Category, Comment, User
from Blog.utils import redirect_back
from Blog.extensions import db
from Blog.form import CommentForm, CommentFormHidden
from Blog.emails import send_someone_connect_email

blog_bp = Blueprint('blog', __name__)

@blog_bp.route('/posts')
def blogs():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/blog.html', pagination=pagination, posts=posts)

@blog_bp.route('/category/<int:category_id>', methods=['GET', 'POST'])
def categories(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.filter_by(category_id=category_id).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', pagination=pagination, posts=posts, category=category)

@blog_bp.route('/post/<param>', methods=['GET'])
def show_post(param):
    post = Post.query.filter_by(title=param).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    comment_pagination = Comment.query.filter_by(post_id=post.id).order_by(Comment.timestamp.desc()).paginate(
        page, per_page)
    comments = comment_pagination.items
    if not current_user.is_anonymous or 'browser_email' in session:
        form = CommentFormHidden()
        form.email.data = current_user.email if not current_user.is_anonymous else session['browser_email']
    else:
        form = CommentForm()
    try:
        form.name.data = current_user.username
    except:
        form.name.data = session['browser_user'] if ('browser_user' in session) else None
    return render_template('blog/post.html', pagination=comment_pagination, post=post, comments=comments, form=form)

@blog_bp.route('/post/<param>/comment', methods=['POST'])
def leave_comment(param):
    post = Post.query.filter_by(title=param).first_or_404()
    email = request.form.get('email', None)
    user = User.query.filter_by(email=email).first()
    if user and not user.confirmed:
        login_user(user)
        session.pop('browser_email',None)
        return redirect(url_for("auth.unconfirmed"))
    if not user:
        author = request.form.get('name', None)
        user = User(username=author, email=email)
    else:
        author = user.username
    body = request.form.get('body', None)
    comment = Comment(body=body, post=post, author_id=user.id)
    db.session.add(comment)
    replied_id = request.form.get('be_reply', None)
    if replied_id:
        replied_comment = Comment.query.get_or_404(replied_id)
        comment.replied = replied_comment
    if request.form.get('remember', None):
        session['browser_email'] = email
        session['browser_user'] = author
    db.session.commit()
    return redirect(url_for('blog.show_post', param=post.title) + '#comments')


@blog_bp.route('/reply')
def reply_comment():
    comment_id = request.args.get('comment_id')
    if comment_id:
        replied_comment = Comment.query.get_or_404(comment_id)
        return render_template('blog/_reply.html', comment=replied_comment)
    print(comment_id)
    return comment_id
    # comment = Comment.query.get_or_404(comment_id)
    # post = Post.query.get_or_404(comment.post_id)
    # print(comment.post_id)
    # if not comment.post.can_comment:
    #     flash('Comment is disabled.', 'warning')
    #     return redirect(url_for('blog.show_post', param=comment.post.title))
    # return redirect(
    #     url_for('blog.show_post', param=post.title, reply=comment_id) + '#comment-form')


@blog_bp.route('/search')
def search():
    q = request.args.get('q', '')
    if q == '':
        flash('Enter keyword about post, user or comment.', 'warning')
        return redirect_back()
    category = request.args.get('category', 'post')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'comment':
        pagination = Comment.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Post.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('blog/search.html', q=q, results=results, pagination=pagination, category=category)


@blog_bp.route('/test')
def test():
    return jsonify({"a":1})

    

Blog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('blog.show_post', param=post.title) }}">{{ post.title }}</a></h3>
        <p>
            {% if post.body_html %}
                {{ post.body_html | safe |striptags|truncate }}
            {% else %}
                {{ post.body|striptags|truncate }}
            {% endif %}
            <small><a href="{{ url_for('blog.show_post', param=post.title) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('blog.show_post', param=post.title) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a href="{{ url_for('.categories',category_id=post.category.id) }}">{{ post.category.name }}</a>&nbsp;&nbsp;
            Time: <a href="#">{{ moment(post.timestamp).format('LL') }}</a>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_admin %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

Blog/templates/blog/_reply.html
<div class="reply_comment alert-dark">
    Reply to <strong>{{ comment.author.username }}</strong>
    <button id="cancel_reply" class="float-right btn btn-outline-danger btn-sm">Cancel</button>
    <p>{{ comment.body }}</p>
</div>

Blog/templates/blog/_search.html
    <div class="card mb-3">
        <form class="form-inline my-2 my-lg-0" action="{{ url_for('blog.search') }}">
            <input type="text" name="q" class="form-control form-control-search" placeholder="Post or category"
                   required>
            <button class="btn btn-light-search" type="submit">
                <span class="oi oi-magnifying-glass"></span>
            </button>
        </form>
    </div>

Blog/templates/blog/_sidebar.html
{% if categories %}
    <div class="card mb-3">
        <div class="card-header">Categories</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.categories',category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

Blog/templates/blog/blog.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_search.html' %}
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

Blog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_search.html' %}
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

Blog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/4.0.0/github-markdown.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/native.css') }}" type="text/css">
<style>
	.markdown-body {
		box-sizing: border-box;
		min-width: 200px;
		max-width: 980px;
		margin: 0 auto;
		padding: 45px;
	}

	@media (max-width: 767px) {
		.markdown-body {
			padding: 15px;
		}
	}
</style>
{% endblock %}

{% block content %}
<div class="page-header">
    <h1>{{ post.title }}
        <span class="float-right">
        {% if current_user.is_admin %}
            <a class="btn btn-info btn-sm" href="{{ url_for('admin.get_post', param=post.title)}}">Edit</a>
            <form class="inline" method="post"
                  action="{{ url_for('admin.delete_post', param=post.title)}}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete
                </button>
            </form>
        {% endif %}
      </span>
    </h1>
    <small>
        Category: <a
            href="{{ url_for('.categories', category_id=post.category_id) }}">{{ post.category.name }}</a><br>
        Date: {{ moment(post.timestamp).format('LL') }}
    </small>
</div>
<div class="row">
    <div class="col-sm-12">
        <div id="article" class="markdown-body">
            {% if post.toc_html %}
                <h1>Content:</h1>
                {{ post.toc_html|safe }}
            <hr>
            {% endif %}
            {% if post.body_html %}
                {{ post.body_html|safe }}
            {% else %}
                {{ post.body }}
            {% endif %}
        </div>

        <hr>
        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#postLinkModal">Share</button>
        <div class="modal fade" id="postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="mySmallModalLabel">Share link</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   value="{{ url_for('blog.show_post', param=post.title, _external=True) | replace_domain('fanco.ink') }}" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="comments" id="comments">
            <h3>There are {{ comments|length }} comments
                {% if current_user.is_admin %}
                <form class="float-right" method="post"
                      action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <button type="submit" class="btn btn-warning btn-sm">
                        {% if post.can_comment %}Disable{% else %}Enable{% endif %} Comment
                    </button>
                </form>
                {% endif %}
            </h3>
            <ul class="list-group">
                {% for comment in comments %}
                <li class="list-group-item list-group-item-action flex-column">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                            <img width="38" height="38" src="{{ comment.author.image }}">
                            <span>{{ comment.author.username }}</span>
                            {# author badge #}
                            {% if comment.author.is_admin %}
                            <span class="badge badge-pill badge-secondary">Author</span>
                            {% endif %}
                        </h5>
                        <small data-toggle="tooltip" data-placement="top" data-delay="500"
                               data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                            {{ moment(comment.timestamp).fromNow() }}
                        </small>
                    </div>
                    {% if comment.replied %}
                    <p class="reply_comment alert-dark reply-body">
                        {{ comment.replied.author.username }} :<br>
                        {{ comment.replied.body }}
                    </p>
                    {%- endif -%}
                    <p class="mb-1">{{ comment.body }}</p>
                    <div class="float-right">
                        <button class="btn btn-dark btn-sm reply" data-reply-id="{{ comment.id }}">Reply</button>
                        {% if current_user.is_admin %}
                        <form class="inline" method="post"
                              action="{{ url_for('admin.delete_comment', comment_id=comment.id)}}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete
                            </button>
                        </form>
                        {% endif %}
                    </div>

                </li>
                {% endfor %}
            </ul>
        </div>
        {% if comments %}
        {{ render_pagination(pagination, fragment='#comments') }}
        {% endif %}

        {% if post.can_comment%}
        <div id="reply_area"></div>
        <div id="comment-form">
            {{ render_form(form, action=url_for('blog.leave_comment', param=post.title)) }}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

Blog/templates/blog/search.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import post_card, user_card, comment_card with context %}

{% block title %}Search: {{ q }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Search: {{ q }}</h1>
        <h5>{{ pagination.total }} results</h5>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
                <a class="nav-item nav-link {% if category == 'post' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='post') }}">Post</a>
                <a class="nav-item nav-link {% if category == 'user' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='user') }}">User</a>
                <a class="nav-item nav-link {% if category == 'comment' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='comment') }}">Comment</a>
                {% include 'blog/_search.html' %}
            </div>
        </div>
        <div class="col-md-9">
            {% if results %}
                {% for item in results %}
                    {% if category == 'post' %}
                        {{ post_card(item) }}
                    {% endif %}
                    {% if category == 'user' %}
                        {{ user_card(item) }}
                    {% endif %}
                    {% if category == 'comment' %}
                        {{ comment_card(item) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <h5 class="tip">No results.</h5>
            {% endif %}
        </div>

    </div>
    {% if results %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='right') }}
        </div>
    {% endif %}
{% endblock %}